export const TREATMENTS = [
  {
    icon: '🪥',
    name: 'Professional Cleaning',
    cost: '₱500 - ₱1,500',
    duration: '45-60 min',
    description: 'Deep cleaning (oral prophylaxis) to remove plaque, tartar, and bacteria buildup. Includes polishing and fluoride treatment.',
    category: 'Preventive',
    gradient: 'from-emerald-500 to-emerald-600',
  },
  {
    icon: '🔧',
    name: 'Dental Filling',
    cost: '₱800 - ₱2,500',
    duration: '30-45 min',
    description: 'Tooth-colored composite resin filling to restore teeth damaged by decay.',
    category: 'Restorative',
    gradient: 'from-blue-500 to-blue-600',
  },
  {
    icon: '👑',
    name: 'Dental Crown',
    cost: '₱8,000 - ₱20,000',
    duration: '2 visits',
    description: 'Custom-made cap (PFM or zirconia) placed over damaged teeth to restore shape, size, and strength.',
    category: 'Restorative',
    gradient: 'from-violet-500 to-violet-600',
  },
  {
    icon: '🦷',
    name: 'Root Canal Treatment',
    cost: '₱3,500 - ₱10,000',
    duration: '1-2 visits',
    description: 'Removal of infected pulp tissue, cleaning, and sealing to save a damaged tooth.',
    category: 'Endodontic',
    gradient: 'from-amber-500 to-amber-600',
  },
  {
    icon: '✨',
    name: 'Teeth Whitening',
    cost: '₱5,000 - ₱12,000',
    duration: '1-2 hours',
    description: 'Professional-grade in-office whitening treatment to brighten teeth by several shades.',
    category: 'Cosmetic',
    gradient: 'from-pink-500 to-pink-600',
  },
  {
    icon: '💎',
    name: 'Porcelain Veneers',
    cost: '₱12,000 - ₱35,000/tooth',
    duration: '2-3 visits',
    description: 'Thin porcelain shells bonded to the front of teeth to improve appearance and symmetry.',
    category: 'Cosmetic',
    gradient: 'from-cyan-500 to-cyan-600',
  },
  {
    icon: '📐',
    name: 'Orthodontic Braces',
    cost: '₱25,000 - ₱55,000',
    duration: '12-24 months',
    description: 'Metal or ceramic braces to straighten crooked or misaligned teeth. Includes regular adjustments.',
    category: 'Orthodontic',
    gradient: 'from-indigo-500 to-indigo-600',
  },
  {
    icon: '🔩',
    name: 'Dental Implant',
    cost: '₱35,000 - ₱100,000',
    duration: '3-6 months',
    description: 'Titanium post surgically placed into the jawbone to replace missing teeth with a permanent solution.',
    category: 'Surgical',
    gradient: 'from-rose-500 to-rose-600',
  },
];

export const KIOSK_TREATMENTS = [
  { id: 'checkup', label: 'General Checkup', duration: 30 },
  { id: 'cleaning', label: 'Teeth Cleaning', duration: 45 },
  { id: 'filling', label: 'Tooth Filling', duration: 45 },
  { id: 'extraction', label: 'Tooth Extraction', duration: 30 },
  { id: 'whitening', label: 'Teeth Whitening', duration: 60 },
  { id: 'braces', label: 'Braces Consultation', duration: 30 },
  { id: 'rootcanal', label: 'Root Canal', duration: 60 },
  { id: 'other', label: 'Other', duration: 30 },
];
