export const TREATMENTS = [
  {
    icon: '🪥',
    name: 'Professional Cleaning',
    cost: '$80 - $150',
    duration: '45-60 min',
    description: 'Deep cleaning to remove plaque, tartar, and bacteria buildup. Includes polishing and fluoride treatment.',
    category: 'Preventive',
    gradient: 'from-emerald-500 to-emerald-600',
  },
  {
    icon: '🔧',
    name: 'Cavity Filling',
    cost: '$150 - $300',
    duration: '30-45 min',
    description: 'Tooth-colored composite resin filling to restore teeth damaged by decay.',
    category: 'Restorative',
    gradient: 'from-blue-500 to-blue-600',
  },
  {
    icon: '👑',
    name: 'Dental Crown',
    cost: '$800 - $1,500',
    duration: '2 visits',
    description: 'Custom-made cap placed over damaged teeth to restore shape, size, and strength.',
    category: 'Restorative',
    gradient: 'from-violet-500 to-violet-600',
  },
  {
    icon: '🦷',
    name: 'Root Canal',
    cost: '$700 - $1,500',
    duration: '1-2 visits',
    description: 'Removal of infected pulp tissue, cleaning, and sealing to save a damaged tooth.',
    category: 'Endodontic',
    gradient: 'from-amber-500 to-amber-600',
  },
  {
    icon: '✨',
    name: 'Teeth Whitening',
    cost: '$300 - $600',
    duration: '1-2 hours',
    description: 'Professional-grade whitening treatment to brighten teeth by several shades.',
    category: 'Cosmetic',
    gradient: 'from-pink-500 to-pink-600',
  },
  {
    icon: '💎',
    name: 'Porcelain Veneers',
    cost: '$900 - $2,500/tooth',
    duration: '2-3 visits',
    description: 'Thin porcelain shells bonded to the front of teeth to improve appearance.',
    category: 'Cosmetic',
    gradient: 'from-cyan-500 to-cyan-600',
  },
  {
    icon: '📐',
    name: 'Orthodontic Alignment',
    cost: '$3,000 - $7,000',
    duration: '12-18 months',
    description: 'Braces or clear aligners to straighten crooked or misaligned teeth.',
    category: 'Orthodontic',
    gradient: 'from-indigo-500 to-indigo-600',
  },
  {
    icon: '🔩',
    name: 'Dental Implant',
    cost: '$2,000 - $5,000',
    duration: '3-6 months',
    description: 'Titanium post surgically placed into the jawbone to replace missing teeth.',
    category: 'Surgical',
    gradient: 'from-rose-500 to-rose-600',
  },
];
